api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", views.getRoutes),
    path("mods/", views.getMods),
    path("mods/<str:pk>", views.getMod),
    path("mods/<str:pk>/vote/", views.modVote),
]

friends/urls.py
from django.urls import path
from . import views


app_name = "friends"
urlpatterns = [
    path("friend_request/<str:pk>", views.send_friend_request, name="send_request"),
    path("requests/", views.show_requests, name="show_requests"),
    path("accept_friend/<str:pk>", views.accept_friend_request, name="accept-friend"),
    path("decline_friend/<str:pk>", views.decline_friend, name="decline-friend"),
    path("unfriend/<str:pk>", views.unfriend_user, name="unfriend"),
    path("cancel_friend/<str:pk>", views.cancel_friend, name="cancel_friend"),
    path("friendlist/<str:user_id>", views.friend_list, name="list_of_friends"),
]

skymoders/urls.py
from re import template
import site
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("mods/", include("projects.urls")),
    path("api/", include("api.urls")),
    path("friends/", include("friends.urls", namespace="friends")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path(
        "reset-password/",
        auth_views.PasswordResetView.as_view(template_name="forget_password.html"),
        name="reset-password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path("login/", views.loginUser, name="login-user"),
    path("logout/", views.logoutUser, name="logout-user"),
    path("register/", views.registerUser, name="register-user"),
    path("", views.showprofiles, name="show-users"),
    path("moders/<str:pk>", views.profile, name="current-profile"),
    path("account/", views.userAccount, name="user-account"),
    path("edit-account/", views.editAccount, name="edit-account"),
    path("delete-account/", views.deleteAcc, name="delete-account"),
    path("add-skill/", views.createSkill, name="add-skill"),
    path("update-skill/<str:pk>", views.updateSkill, name="update-skill"),
    path("delete-skill/<str:pk>", views.deleteSkill, name="delete-skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<str:pk>", views.inboxMassage, name="selected-message"),
    path("send-message/<str:pk>", views.sendMessage, name="send-message"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField


def validation_file(value):
    if not value.name.endswith((".zip", ".rar", ".7z")):
        raise ValidationError("Only Zip and rar are allowed")


class Mod(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = RichTextField()
    short_intro = models.TextField(max_length=200, blank=False, null=False)
    version = models.CharField(max_length=10, blank=False, null=False)
    featured_image = models.ImageField(
        null=True, blank=True, upload_to="modtitle/", default="default.png"
    )
    modfile = models.FileField(upload_to="files/", validators=[validation_file])
    view_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(null=True, default=0, blank=True)
    vote_ration = models.IntegerField(null=True, default=0, blank=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-vote_total", "-vote_ration", "-title"]

    @property
    def getVoters(self):
        voters = self.review_set.all().values_list("owner__id", flat=True)
        return voters

    @property
    def getImage(self):
        try:
            url = self.featured_image.url
        except:
            url = ""
        return url

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value="up").count()
        totalVotes = reviews.count()
        if totalVotes == 0:
            return
        ration = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ration = round(ration, 2)
        self.save()


class Review(models.Model):
    VOTE_TYPE = (("up", "Up Vote"), ("down", "Down Vote"))
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    mod = models.ForeignKey(Mod, on_delete=models.CASCADE)
    created = models.TimeField(auto_now_add=True)
    body = models.TextField(max_length=200, null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False, primary_key=True
    )

    class Meta:
        unique_together = [["owner", "mod"]]

    def __str__(self) -> str:
        return self.value


class Gallery(models.Model):
    id = models.AutoField(primary_key=True)
    parent = models.ForeignKey(Mod, null=True, blank=True, on_delete=models.CASCADE)
    user_owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True
    )
    img = models.ImageField(null=True, blank=True, upload_to="modgallery/")
    title = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.parent} {self.id}"


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.TimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from ckeditor.fields import RichTextField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=15, blank=True, null=True)
    email = models.CharField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=500, blank=True, null=True)
    region = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    short_bio = models.TextField(max_length=200, blank=False, null=False)
    bio = RichTextField(config_name="simple_toolbar")
    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to="profiles/",
        default="profiles/default-user.png",
    )
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        ordering = ["-created"]

    def get_profile_img(self):
        try:
            url = self.profile_image.url
        except:
            url = ""
        return url


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)
    created = models.TimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True
    )
    receiver = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(max_length=500, null=True, blank=True)
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ["-is_read", "-created"]

users/forms.py
from dataclasses import field
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "email", "username", "password1", "password2"]
        labels = {
            "first_name": "Name",
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for key, value in self.fields.items():
            value.widget.attrs.update({"class": "input"})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            "name",
            "email",
            "username",
            "region",
            "short_intro",
            "short_bio",
            "bio",
            "profile_image",
        ]

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.items():
            field.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: var(--color-sub-light);color: var(--color-light);",
                }
            )


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = "__all__"
        exclude = ["owner"]

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for key, value in self.fields.items():
            value.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: var(--color-sub-light); color: var(--color-light);",
                }
            )


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ["sender", "receiver", "is_read", "name", "email"]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.items():
            field.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: var(--color-sub-light); color: var(--color-light);",
                }
            )

users/templates/users/account.html
{% extends 'main.html'%}
{% block content %}

  <style>
    .settings__table tr:not(:last-child) td {
      border-bottom: 2px solid rgb(253, 253, 253);
    }
    p.devInfo__about  {
      font-family: inherit  !important;
    }
  </style>
  <main class="settingsPage profile" style="margin: none;">
    <div class="container" style="background-color: var(--color-sub);">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center" style="border: 2px solid var(--color-sub-light); background-color: black;">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}?next=/account/" style=" background: var(--color-sub); color: white;"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-account' %}?next=/account/" style=" background: var(--color-sub); color: white;"><i class="im im-x-mark-circle-o"></i> Delete</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.get_profile_img }}" />
              <h2 class="dev__name" style="color: var(--color-light);">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.region}}</p>
              <ul class="dev__social">
                {% if acc_friends == 1%}
                <li>
                    <a title="Friend" href="{% url 'friends:list_of_friends' user_id=profile.id %}" style="color: white;">
                      <i class='fas fa-user-friends'> {{ acc_friends }}</i> </a>
                </li>
                {% elif acc_friends > 1 %}
                <li>
                    <a title="Friends" href="{% url 'friends:list_of_friends' user_id=profile.id %}" style="color: white;">
                      <i class='fas fa-user-friends' style="color: white;"> {{ acc_friends }}</i ></a>
                </li>
                {% else %}
                <li>
                    <a title="Friends" href="{% url 'friends:list_of_friends' user_id=profile.id  %}">
                      <i class='fas fa-user-friends' style="color: white;"> {{ acc_friends }}</i> </a>
                </li>
                {% endif %}
                <li>
                  <a title="Requests" href="{% url 'friends:show_requests' %}" 
                style="color: white;" class="friend-requests .request-btn-row .friends">
                <i class="fa-solid fa-person-circle-question"> {{friend_requests | length}}</i>
              </a>
                </li> 
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo" style="margin: 15px;">
            <h3 class="devInfo__title" style="color: var(--color-light);">About Me</h3>
            <p class="devInfo__about">{{profile.bio| safe}}</p>
          </div>
          <div class="settings" style="margin: 15px;">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'add-skill' %}?next=/account/"
            style=" background: black;color: white;"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table" style="border: 2px solid var(--color-sub-light); background-color: black; margin: 15px;">
            {%for skill in skills%}
            <tr>
              <td class="settings__tableInfo">
                <h4 style="color: var(--color-light);">{{skill.name}}</h4>
                <p>
                  {{skill.description|slice:"150"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}?next=/account/" style=" background: var(--color-sub);color: white;">
                  <i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account/" style=" background: var(--color-sub);color: white;">
                  <i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}

             
          </table>

          <div class="settings" style="margin: 15px;">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-mod' %}"
            style=" background: black;color: white;"><i class="im im-plus"></i> Add mod</a>
          </div>

          <table class="settings__table" style="border: 2px solid var(--color-sub-light); background-color: black; margin: 15px;">
            {% for mod in mods %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'modpage' mod.id %}"><img src="{{mod.getImage}}" alt="Mod Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'modpage' mod.id %}" style="color: var(--color-light);">{{ mod.title }}</a>
                <p>
                  {{ mod.short_intro|slice:'150'|safe }}
                  {% if mod.short_intro|length > 150 %}...{% endif %}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-mod' mod.id %}?next=/account/" style=" background: var(--color-sub);color: white;"
                ><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-mod' mod.id %}?next=/account/" style=" background: var(--color-sub);color: white;"
                ><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/edituser.html
{% extends 'main.html' %}
{% block content %}
<h1>Edit account</h1>

<form method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submits"/>
</form>


{% endblock %}

users/templates/users/form-template.html
{% extends 'main.html'%}
{% load static %}
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% block content %}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper" style="background-color: var(--color-sub);">
                <a class="backButton" style=" background: var(--color-sub-light);color: white;" href="{{request.GET.next}}"><</a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.media}}
                    {% for field in form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text" style="color: var(--color-light)">{{field.label}}: </label>
                        {{field}}
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}
{% block content %}
<style>
  li.message.message--unread > a span {
  color: var(--color-white);
}

</style>


  <main class="inbox my-xl">
    <div class="content-box" style="background-color: #27172e69;">
      <h3 class="inbox__title" style="color: var(--color-light)">New Messages(<span style="color: #67968bbd;">{{unread}}</span>)</h3>
      <ul class="messages" style="background-color: black;">
        {% for mes in messagesRequest %}
        {% if mes.is_read == False%}
        <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}
          <a href="{% url 'selected-message' mes.id %}?next=/inbox/">
            {% if mes.sender %}
            <span class="message__author">{{mes.sender}}</span>
            {% else %}
            <span class="message__author">Deleted user</span>
            {% endif %}
            <span class="message__subject">{{mes.subject}}</span>
            <span class="message__date">{{mes.created}}</span>
          </a>
        </li>
        {% endfor %}

      </ul>
    </div>
  </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'main.html' %}

{% block content %}
<head>
    <script src="https://kit.fontawesome.com/95f8f67f8f.js" crossorigin="anonymous"></script>
</head>
<main class="profile">
    <div class="container" style="background-color: var(--color-sub);">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center" style="border: 2px solid var(--color-sub-light); background-color: black;">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ moder.get_profile_img }}" />
              <h2 class="dev__name" style="color: var(--color-light);">{{moder.name }}</h2>
              <p class="dev__title">{{moder.short_intro}}</p>
              <p class="dev__location">Region {{moder.region}}</p>
              
              {% if is_friend %}
                <a href="{% url 'send-message' pk=moder.id %}?next={% url 'current-profile' pk=moder.id %}">
                  <i class="fa-regular fa-envelope fa-xl" style="color: #ffffff; font-size: 3em; margin-top: 40px;"></i></a>
              {% elif is_friend == False and is_self %}
                <a href="{% url 'friends:show_requests' %}" class="btn btn--main  btn--sub" 
                style=" background: var(--color-sub);color: white; margin: 5%;">Friend requests {{friend_requests | length}} </a>
              {%endif%}

              {% if request_sent == 0 %}
              <ul class="dev__social" style="background-color: white; border-radius: 10px; border-color: var(--color-main);">
                <li >
                    <a>
                        <a style="color: var(--color-text); color: var(--color-sub);">
                            Accept Friend Request
                        </a>
                        <br>
                        <a style="margin-left: 10px;  color: var(--color-sub);" href="{% url 'friends:accept-friend' pk=request_id %}">
                          <i class='fas fa-user-check'></i></a>
                        <a style="margin-left: 30%; color: var(--color-sub);" href="{% url 'friends:decline-friend' pk=request_id %}?next={% url 'current-profile' pk=moder.id %}">
                          <i class='fas fa-user-minus'></i></a>
                    </a>
                </li>

              </ul>
              {% elif is_friend == False and is_self == False %}
                {% if request_sent == 1 %}
                  <a href="{% url 'friends:cancel_friend' pk=moder.id %}?next={% url 'current-profile' pk=moder.id %}" class="btn btn--main btn"
                   style=" background: var(--color-sub);color: white; margin-top: 10px;">Cancel friend request</a>
                {% endif %}
                {% if request_sent == -1 %}
                  <a href="{% url 'friends:send_request' pk=moder.id %}" class="btn btn--main btn" 
                  style="background-color: var(--color-light); color: var(--color-sub); margin-top: 10px;">Send friend request</a>
                {% endif %}
              {% endif %}

              <ul class="dev__social" >
                {% if acc_friends == 1%}
                <li>
                    <a href="{% url 'friends:list_of_friends' user_id=moder_id %}" style="color: white;">
                      <i class='fas fa-user-friends'></i> {{ acc_friends }} friend </a></i>
                </li>
                {% elif acc_friends > 1 %}
                <li>
                    <a href="{% url 'friends:list_of_friends' user_id=moder_id %}" style="color: white;">
                      <i class='fas fa-user-friends'></i> {{ acc_friends }} friends </a></i>
                </li>
                {% else %}
                <li>
                    <a><i class='fas fa-user-friends' style="color: white;"></i> {{ acc_friends }} friends </a></i>
                </li>
                {% endif %}
                {% if is_friend %}
                  <a href="{% url 'friends:unfriend' pk=moder.id %}?next={% url 'current-profile' pk=moder.id %}" style="color: white;">
                    Remove <i class="fa-solid fa-user-minus"></i></a>
                {% endif %}
                
              </ul>
             
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo" style="margin: 15px;">
            <h3 class="devInfo__title" style="color: var(--color-light); margin: 15px;">About Me</h3>
            <p class="devInfo__about">{{moder.bio| safe}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title" style="color: var(--color-light); margin: 10px;">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in specSkill %}
              <div class="devSkill">
                <h4 class="devSkill__title" style="margin: 15px;">{{skill.name}}</h4>
                <p class="devSkill__info" style="margin: 15px;">{{skill.description}}</p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle" style="color: var(--color-light); margin: 10px;">Other Skills</h3>
              <div class="devInfo__otherSkills" style="margin: 15px;">
                {% for extra in addskills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small><a href="{% url 'show-users' %}?search_query={{extra}}">{{extra}}</a></small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo" style="margin: 15px;">
            <h3 class="devInfo__title" style="color: var(--color-light);">Projects</h3>
            <div class="grid grid--two">
              {% for mod in moder.mod_set.all %}
              <div class="column">
                <div class="card project" style="border: 2px solid var(--color-sub-light); background-color: black;">
                  <a href="{% url 'modpage' mod.id %}" class="project">
                    <img class="project__thumbnail" src="{{mod.getImage}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title" style="color: var(--color-light);">{{mod.title}}</h3>
                      <p><a class="project__author" href="{% url 'current-profile' moder.id %}" style="color: var(--color-light);">By {{mod.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{mod.vote_ration}}%</span> Postitive
                        Feedback ({{mod.vote_total}} Vote{{mod.vote_total|pluralize:"s"}})
                      </p>
                      
                      <div class="project__tags">
                        {% for tag in mod.tags.all %}
                        <span class="tag tag--pill tag--sub tag">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                      
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">

                <form id="searchForm" class="form" action="{% url 'show-users' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            value="{{search_query}}" placeholder="Search by developer name" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>

            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">

                {% for profile in moders %}
                <div class="column card" style="background-color: black;">
                    <div class="dev">
                        <a href="{% url 'current-profile' profile.id  %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ profile.get_profile_img  }}" alt="image" />
                                <div class="dev__meta">
                                    <h3 style="color: var(--color-light)">{{profile.name}}</h3>
                                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{ profile.short_bio|slice:'150'|safe }}
                              {% if profile.short_bio|length > 150 %}...{% endif %}</p>
                            <div class="dev__skills">
                                {% for skill in profile.skill_set.all|slice:"5"%}
                                <span class="tag tag--pill tag--sub tag">
                                  <small>{{ skill.name }}</small>
                                </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}
</main>

{% endblock content %}

users/templates/users/skilladd.html
{% extends 'main.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        {{field.label}}
        {{field}}
    {% endfor %}
    <input type="submit" value="Submit">

</form>
{% endblock %}