api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", views.getRoutes),
    path("mods/", views.getMods),
    path("mods/<str:pk>", views.getMod),
    path("mods/<str:pk>/vote/", views.modVote),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.showmods, name="home"),
    path("mod/<str:pk>/", views.currentmod, name="modpage"),
    path("create-mod/", views.createMod, name="create-mod"),
    path("update-mod/<str:pk>/", views.updateMod, name="update-mod"),
    path("delete-mod/<str:pk>/", views.deleteMod, name="delete-mod"),
    path("gallery/<str:pk>/", views.modGallery, name="gallery"),
    path("gallery/addimages/<str:pk>", views.addImage, name="add-images"),
    path("update-gallery/<str:pk>", views.editGallery, name="edit-gallery"),
    path("gallery/delete/<str:pk>", views.deleteImg, name="delete-img"),
    path("mod/download/<str:pk>/", views.download_view, name="downloadmod"),
    path("gallery/change_image/<str:pk>/", views.change_img, name="change_image"),
]

skymoders/urls.py
from re import template
import site
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("mods/", include("projects.urls")),
    path("api/", include("api.urls")),
    path("friends/", include("friends.urls", namespace="friends")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path(
        "reset-password/",
        auth_views.PasswordResetView.as_view(template_name="forget_password.html"),
        name="reset-password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/models.py
from django.db import models
import uuid
from users.models import Profile
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField


def validation_file(value):
    if not value.name.endswith((".zip", ".rar", ".7z")):
        raise ValidationError("Only Zip and rar are allowed")


class Mod(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = RichTextField()
    short_intro = models.TextField(max_length=200, blank=False, null=False)
    version = models.CharField(max_length=10, blank=False, null=False)
    featured_image = models.ImageField(
        null=True, blank=True, upload_to="modtitle/", default="default.png"
    )
    modfile = models.FileField(upload_to="files/", validators=[validation_file])
    view_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(null=True, default=0, blank=True)
    vote_ration = models.IntegerField(null=True, default=0, blank=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-vote_total", "-vote_ration", "-title"]

    @property
    def getVoters(self):
        voters = self.review_set.all().values_list("owner__id", flat=True)
        return voters

    @property
    def getImage(self):
        try:
            url = self.featured_image.url
        except:
            url = ""
        return url

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value="up").count()
        totalVotes = reviews.count()
        if totalVotes == 0:
            return
        ration = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ration = round(ration, 2)
        self.save()


class Review(models.Model):
    VOTE_TYPE = (("up", "Up Vote"), ("down", "Down Vote"))
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    mod = models.ForeignKey(Mod, on_delete=models.CASCADE)
    created = models.TimeField(auto_now_add=True)
    body = models.TextField(max_length=200, null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False, primary_key=True
    )

    class Meta:
        unique_together = [["owner", "mod"]]

    def __str__(self) -> str:
        return self.value


class Gallery(models.Model):
    id = models.AutoField(primary_key=True)
    parent = models.ForeignKey(Mod, null=True, blank=True, on_delete=models.CASCADE)
    user_owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True
    )
    img = models.ImageField(null=True, blank=True, upload_to="modgallery/")
    title = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.parent} {self.id}"


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.TimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.name

projects/forms.py
from dataclasses import field, fields
from django.forms import ModelForm, widgets
from django import forms
from .models import Mod, Review, Gallery
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class ModForm(ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget(config_name="default"))

    class Meta:
        model = Mod
        fields = [
            "title",
            "featured_image",
            "short_intro",
            "description",
            "modfile",
            "tags",
        ]
        widgets = {
            "tags": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ModForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: var(--color-sub-light); color: var(--color-light);",
                }
            )


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["value", "body"]
        labels = {"value": "Place u'r vote", "body": "Add a comment with u'r vote"}

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: var(--color-sub-light); color: var(--color-light);",
                }
            )


class ImageForm(ModelForm):
    class Meta:
        model = Gallery
        fields = ["img", "title"]

    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.widget.attrs.update(
                {
                    "class": "input",
                    "style": "background-color: #1c19218f; color: var(--color-light);",
                }
            )

projects/views.py
import users
import os
import mimetypes
import pathlib

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from users.views import profile


from . import utils
from .models import Mod, Gallery
from .forms import ModForm, ReviewForm, ImageForm


def convert_bytes(size):
    """Convert bytes to KB, or MB or GB"""
    for x in ["bytes", "KB", "MB", "GB", "TB"]:
        if size < 1024.0:
            return "%3.1f%s" % (size, x)
        size /= 1024.0


def showmods(request):
    data, search_query = utils.modSearch(request)
    mods, custom_range = utils.modPaginate(request, data, 6)

    context = {"mods": mods, "search_query": search_query, "custom_range": custom_range}
    return render(request, "projects/modpage.html", context)


def currentmod(request, pk):
    data = Mod.objects.get(id=pk)
    print(pk)
    data.view_count += 1
    data.save()
    form = ReviewForm()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.mod = data
        review.owner = request.user.profile
        review.save()
        messages.success(request, "U'r review was successfully submitted")
        return redirect("modpage", pk=data.id)

    file_path = data.modfile.path
    try:
        os.path.exists(file_path)
        f_size = os.path.getsize(file_path)
        size = convert_bytes(f_size)
    except:
        size = "0.0 bytes"

    if data.getVoteCount:
        data.getVoteCount

    context = {"mod": data, "form": form, "size": size}
    return render(request, "projects/currentmod.html", context)


@login_required(login_url="login-user")
def createMod(request):
    profile = request.user.profile

    forms = ModForm()
    if request.method == "POST":
        print(request.POST)
        forms = ModForm(request.POST, request.FILES)
        if forms.is_valid():
            mod = forms.save(commit=False)
            mod.owner = profile
            mod.save()
            return redirect("home")

    context = {"forms": forms}
    return render(request, "projects/form-template.html", context)


@login_required(login_url="login-user")
def updateMod(request, pk):
    profile = request.user.profile
    mod = profile.mod_set.get(id=pk)
    forms = ModForm(instance=mod)

    if request.method == "POST":
        forms = ModForm(request.POST, request.FILES, instance=mod)
        if forms.is_valid():
            forms.save()
            return redirect("user-account")

    context = {"forms": forms}
    return render(request, "projects/form-template.html", context)


@login_required(login_url="login-user")
def download_view(request, pk):
    try:
        file_instance = Mod.objects.get(id=pk)
    except Mod.DoesNotExist:
        messages.error(request, "File not found.")
        return redirect("modpage", pk=file_instance.id)

    file_path = file_instance.modfile.path
    file_name = os.path.basename(file_path)
    original_extension = os.path.splitext(file_name)[1]

    # Set the content type based on the file extension
    content_type, _ = mimetypes.guess_type(file_path)
    if content_type is None:
        content_type = "application/octet-stream"

    response = HttpResponse(content_type=content_type)
    response["Content-Disposition"] = f'attachment; filename="{file_name}"'

    try:
        with open(file_path, "rb") as f:
            response.write(f.read())

        messages.success(request, "File is successful downloaded.")
        return response

    except Exception as e:
        messages.error(request, f"File download failed: {str(e)}")
        return redirect("modpage", pk=file_instance.id)


@login_required(login_url="login-user")
def deleteMod(request, pk):
    profile = request.user.profile
    mod = profile.mod_set.get(id=pk)
    if request.method == "POST":
        mod.delete()
        return redirect("user-account")
    context = {"obj": mod}
    return render(request, "delete.html", context)


def modGallery(request, pk):
    filtro = request.GET.get("imageFilter")
    try:
        mod = Mod.objects.get(id=pk)
        images = mod.gallery_set.all()

        if filtro == "mod_owner":
            images = images.filter(user_owner=mod.owner)
        elif filtro == "users":
            images = images.exclude(user_owner=mod.owner)
    except:
        pass
    images, custom_range = utils.modPaginate(request, images, 6)
    context = {
        "mod": mod,
        "images": images,
        "custom_range": custom_range,
        "imageFilter": filtro,
    }
    print(request.user, mod.owner)
    return render(request, "projects/gal.html", context)


@login_required(login_url="login-user")
def addImage(request, pk):
    mod = Mod.objects.get(id=pk)
    print(mod)
    if request.method == "POST":
        images = request.FILES.getlist("images")
        for i in images:
            item = Gallery.objects.create(
                parent=mod, user_owner=request.user.profile, img=i
            )
            item.save()
        return redirect("edit-gallery", pk=pk)
    context = {"page": "addimage"}
    return render(request, "projects/form-template.html", context)


@login_required(login_url="login-user")
def editGallery(request, pk):
    mod = Mod.objects.get(id=pk)
    filtro = ""
    if request.user == mod.owner.user:
        images = mod.gallery_set.all()
        filtro = request.GET.get("imageFilter")
        if filtro == "mod_owner":
            images = images.filter(user_owner=mod.owner)
        elif filtro == "users":
            images = images.exclude(user_owner=mod.owner)
        print("tyt")
    else:
        profile = request.user.profile
        images = mod.gallery_set.all().filter(user_owner=profile.id)
        print("ne tyt")

    images, custom_range = utils.modPaginate(request, images, 6)
    context = {
        "page": "page",
        "mod": mod,
        "images": images,
        "custom_range": custom_range,
        "imageFilter": filtro,
    }
    return render(request, "projects/gal.html", context)


@login_required(login_url="login-user")
def change_img(request, pk):
    img = get_object_or_404(Gallery, id=pk)
    mod = img.parent.id
    if request.user == img.user_owner.user:
        form = ImageForm(instance=img)
        if request.method == "POST":
            form = ImageForm(request.POST, request.FILES, instance=img)
            if form.is_valid():
                form.save()
                return redirect("edit-gallery", pk=mod)
    else:
        messages.error(request, "U can't change another user image")
        return redirect("edit-gallery", pk=mod)
    context = {"form": form, "img": img, "page": "change"}
    return render(request, "projects/form-template.html", context)


@login_required(login_url="login-user")
def deleteImg(request, pk):
    img = Gallery.objects.get(id=pk)
    mod = img.parent.id
    if request.method == "POST":
        img.delete()
        return redirect("edit-gallery", pk=mod)
    context = {"obj": img, "page": "img"}
    return render(request, "delete.html", context)

projects/templates/projects/currentmod.html
{% extends 'main.html' %}
{% block content %}
<style>
  table {
    border-collapse: collapse;
    
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
  }
  tr {
    border: none;
  }
  th, td {
    padding: 15px;
    text-align: left;
    border-bottom: 1px solid #0b0a0ad4;
  }

  th {
    background-color: #333;
    color: white;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
  }

  .eye-icon, .file-icon {
    font-size: 18px;
    margin-right: 5px;
  }
  textarea#id_body {
    background-color: black;
    border: solid gray;
  }
  select#id_value {
    background-color: black;
    border: solid gray;
  }
</style>
<body class="mod-body">
  <!-- Main Section -->
  <main class="singleProject my-md" style="margin: auto;">
    <div class="container" style="background-color: var(--color-sub);">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle" style="color: aliceblue; margin: 2pc;">Tags for this mod</h3>
          <div class="singleProject__toolStack">
            {% for tag in mod.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg" style="margin-left: 10%;">
              <small><a href="/mods/?search_query={{tag}}">{{tag}}</a></small>
            </span>
            {% endfor %}
          </div>
          <a class="singleProject__liveLink" href="{% url 'gallery' mod.id %}?next={{request.path}}"  style="margin-left: 15%; justify-content: space-between;"><i class="im im-external-link"></i>Mod gallery
          </a>
          {% if mod.modfile %}
          <a class="singleProject__liveLink" href="{% url 'downloadmod' pk=mod.id %}" ><i class="im im-external-link"></i>Download
          </a>
          {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ mod.getImage }}" alt="portfolio thumbnail" />
          <br>
          <table style="color: var(--color-light-gray);">
            <tr>
              <td >Uploaded by</td>
              <td style="padding: 5px;">Mod author</td>
              <td >Total views</td>
              <td style="padding: 5px;">File size</td>
              <td style="padding: 5px;">Date uploaded</td>
              <td style="padding: 5px;">Version</td>
              <td  >Last updated</td>
            </tr>
            <tr>
              <td><a href="{% url 'current-profile' mod.owner.id %}"> {{ mod.owner }} </a></td>
              <td>{{ mod.owner }}</td>
              <td><i class="fa-solid fa-eye"></i> {{mod.view_count}} </td>
              <td><p >{{size}}</i></p></td>
              <td >{{mod.created}} </td>
              <td >{{mod.version}} </td>
              <td>{{mod.updated}} </td>
            </tr>
          </table>
          <h2 class="singleProject__title" style="color: aliceblue;">{{mod.title}}</h2>
          {% if mod.description %}
            <p>{{mod.short_intro}}</p>
            <br>
            <h3 class="singleProject__subtitle" style="color: aliceblue;">About the Mod</h3>
            <div class="singleProject__info" style="margin: 15px;">
              {{mod.description| safe}}
            </div>
          {% endif %}
          <div class="comments">
            <h3 class="singleProject__subtitle" style="color: aliceblue;">Feedback</h3>
            <h5 class="project--rating">
              {{mod.vote_ration}}% Postitive Feedback ({{mod.vote_total}} Vote{{mod.vote_total|pluralize:"s"}})
            </h5>
            {% if request.user.profile.id in mod.getVoters%}
              <p>U have already submited review for this project</p>
            {% elif request.user.profile == mod.owner %}
              <p>U  can't review u'r own work </p>
            {% elif request.user.is_authenticated %}

            <form class="form" action="{% url 'modpage' mod.id %}" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <!-- Textarea -->
              <div class="form__field" >
                <label for="formInput#textarea" style="background-color: black;">{{field.label}}</label>
                {{field}}
              </div>
              {% endfor %}
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
              
            </form>
            {% else %}
              <a href="{% url 'login-user' %}?next={{request.path}}">Login to leave a review</a>
            {% endif %}
            <div class="commentList">
              {% for review in mod.review_set.all %}
              {% if review.body %}
              <div class="comment">
                <a href="{% url 'current-profile' review.owner.id %}">
                  <img class="avatar avatar--md"
                    src="{{review.owner.profile_image.url }}" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="{% url 'current-profile' review.owner.id %}" class="comment__author">{{review.owner.name}}</a>
                  <p class="comment__info">{{review.body|linebreaksbr}}</p>
                </div>
              </div>
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
</body>
{% endblock %}

projects/templates/projects/form-template.html
{% extends 'main.html' %}
{% block content %}
<body>
    <main class="formPage my-xl" >
        <div class="content-box">
            <div class="formWrapper" 
            {% if page %}
            style="background-color: #00000096; border: 1.5px solid #dbc089ad;" 
            
            {% else%}
            style="background-color: var(--color-sub);"
            {% endif %}>
                <a class="backButton"
                    {% if page %}
                        style="background-color: #00000096; border: 1.5px solid #dbc089ad;" 
            
                    {% else%}
                        style=" background: var(--color-sub-light);color: white;" 
                    {% endif %} 
                 href="{{request.GET.next}}"><</i></a>
                <br>
                {% if page == 'change' %}
                <body class="gal-body">
                    <h2 style="color: #dbc089ad;">Change Image</h2>   
                    <form class="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <input  class="btn btn--sub btn--lg  my-md" type="submit" value="Change Image" style="background-color: #1c19218f;
                    color: #dbc089ad;">
                    </form>
                </body>
                
                {% elif page %}
                <body class="gal-body"> 
                    <form method="POST" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <label style="color: #dbc089ad;">Upload images</label>
                        <input required name="images" type="file" multiple/>
                        <input class="btn btn--sub btn--lg  my-md" type="submit" value="Upload" style="background-color: #1c19218f;
                        color: #dbc089ad;" />
                    </form>
                </body>
                {% else %}
                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{forms.media}}
                    {% for field in forms %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text" style="color: var(--color-light)">{{field.label}}</label>
                        {{field}}
                     
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                    
                </form>
                {% endif %}
            </div>
        </div>
    </main>
</body>

{% endblock %}

projects/templates/projects/gal.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<head>
    <title>Tutorial</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/lightbox.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/images.css' %}">
    
    <script
      type="text/javascript"src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
</head>
<style>
body{
    background-image: url(/static/images/patt.jpg);
    background-size: cover;
    min-height: 100vh;
    background-repeat: no-repeat;
}

.project__thumbnail {
    filter: grayscale(100%);
    transition: filter 0.5s ease;
}

.project__thumbnail:hover {
    filter: none;
}

#imageFilterForm {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
  
}


#imageFilterForm {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
}

.filter-form {
  text-align: center;
  background-color: #383838a1;
  padding: 20px;
  border-radius: 8px;
}

label {
  font-size: 16px;
  font-weight: bold;
  color: #dbc089ad;
  margin-right: 10px;
}

select {
  padding: 8px;
  font-size: 14px;
  border: 1px solid #0c0c0c;
  border-radius: 5px;
  outline: none;
  background: #0000002b url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='16' height='16'%3E%3Cpath fill='%23dbc089ad' d='M6 10l10 12 10-12z'%3E%3C/path%3E%3C/svg%3E") right 8px center no-repeat;
  color: #dbc089ad;
  /* Remove default arrow */
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  /* Style custom arrow */
  background-size: 16px 16px;
  padding-right: 30px; /* Add space for the arrow icon */
}

/* Add styles for the expanded dropdown */
select:focus {
  border-color: #dbc089ad; /* Change border color when focused */
  background-color: #0000002b; /* Set background color when expanded */
  color: #dbc089ad; /* Keep the text color */
}

option {
  background-color: #000000; /* Set background color for the options */
  color: #d19723ad; /* Set text color for the options */
}

.bnt{
  padding: 8px 16px;
  font-size: 14px;
  background-color: #01040df2;
  color: #dbc089ad;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

bnt:hover {
  background-color: #00000096;
}
</style>
  {% if page and request.user == mod.owner.user or not page %}
  <form id="imageFilterForm">
    <label for="imageFilter">Filter images:</label>
    <select name="imageFilter" id="imageFilter" value="{{imageFilter}}">
      <option value="all">All Images</option>
      <option value="mod_owner">Images Added by Mod Owner</option>
      <option value="users">Images Added by Users</option>
    </select>
    <button type="submit" class="bnt">Filter</button>
  </form>
  {% endif %}
  <h1 style="text-align: center; color: #dbc089ad;">{{mod.title}}</h1>
  <h2 style="text-align: center; color: #dbc089ad;">Gallery
  
    {% if not page %}
    <a href="{% url 'edit-gallery' mod.id%}?next={{request.path}}"><i class="fa-solid fa-gear" style="color: #e4e4e4ad;"></i></a>
    {% else %}
    <a href="{% url 'add-images' mod.id %}?next={{request.path}}"><i class="fa-solid fa-folder-plus" style="color: #e4e4e4ad;"></i></a>
    {% endif %}
    </i>
  </h2>
<section class="projectsList" style="margin-top: 0%;">
    
    <div class="container" >
        <div class="grid grid--three">

            {% for image in images %}
            <div class="column" >
                <div class="card project" style="background-color: black;">

                    <a href="{{image.img.url}}" data-lightbox="mygallery"><img src="{{image.img.url}}" class="project__thumbnail"/></a>
                    <div class="card__body">
                        {% if image.title %}
                        <h3 class="project__title" style="color: var(--color-light)">{{image.title}}</h3>
                        {% else %}
                        <h3 class="project__title" style="color: var(--color-light)">Added image</h3>
                        {%endif%}
                        <p><a class="project__author" href="{% url 'current-profile' image.user_owner.id %}" style="color: var(--color-light);">
                          {% if image.user_owner == mod.owner %}
                            By mod author
                          {% else %}
                            By {{image.user_owner}}
                          {% endif %}
                        </a>
                        </p>
                        {% if page %}
                        <p>
                          {% if request.user == image.user_owner.user %}
                          <a href="{% url 'change_image' image.id %}?next={{request.path}}" class="bnt">
                            <i class="fa-solid fa-arrow-right-arrow-left"></i></ia>
                          {% endif %}
                          <a href="{% url 'delete-img' image.id %}?next={{request.path}}" class="bnt">
                            <i class="fa-solid fa-folder-minus"></i></a>
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

{% include 'pagination.html' with queryset=images custom_range=custom_range  page='gallery'%}

</main>
{% endblock %}

projects/templates/projects/register.html
{% extends 'main.html' %}
{% block content %}
<h1>Project form</h1>
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit">

</form>
{% endblock %}